#!/bin/bash

# Install hadolint
wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64
chmod +x hadolint
sudo mv hadolint /usr/local/bin/

# Run hadolint on Dockerfile
hadolint Dockerfile
